language: c

sudo: required
dist: focal

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_script:
- git fetch --unshallow --tags -q

script:
- cmake .
  && make
  && sudo make install
